# Generated by Django 3.2.12 on 2022-03-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('animal_type', models.CharField(choices=[('Gecko', 'Gecko'), ('Frog', 'Frog'), ('Fish', 'Fish')], max_length=20)),
                ('age', models.IntegerField()),
                ('acquire_date', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=20)),
                ('mother', models.CharField(max_length=100, null=True)),
                ('father', models.CharField(max_length=100, null=True)),
                ('morph', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Animals',
            },
        ),
    ]
