# Generated by Django 3.2.12 on 2022-03-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='acquire_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='cost',
            field=models.FloatField(),
        ),
    ]
